"""create table

Revision ID: f0dc09e3750d
Revises: 
Create Date: 2024-01-05 16:24:01.079073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0dc09e3750d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus_point',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('buyers',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('number', sa.String(length=11), nullable=False),
    sa.Column('date_registered', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('bonus_points', sa.Integer(), nullable=False),
    sa.Column('count_aplications', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('employees',
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('date_registered', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('cheques',
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('films', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('employee', sa.Integer(), nullable=False),
    sa.Column('buyer', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyer'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['employee'], ['employees.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cheques')
    op.drop_table('employees')
    op.drop_table('buyers')
    op.drop_table('bonus_point')
    # ### end Alembic commands ###
