version: "3.11"

services:
   db:
      image: postgres:latest
      restart: always
      env_file: 
         - .env

   bot:
      build: .
      env_file:
         - .env
      depends_on:
         - db
      command: sh -c "./wait-for-postgres.sh db && alembic upgrade head && python main.py"
