version: "3.11"

services:
   db:
      image: postgres:latest
      restart: always
      env_file: 
         - .env
      ports:
         - 5432:5432

   bot:
      build: .
      env_file:
         - .env
      depends_on:
         - db
      command: sh -c "wait-for-postgres.sh && alembic upgrade head && python main.py"
