version: "3.11"

services:
   db:
      image: postgres:latest
      # restart: always
      env_file: 
         - .env
      # volumes:
      #    - pgdata:/var/lib/postgresql/data
      ports:
         - 5432:5432

   bot:
      build: .
      env_file:
         - .env
      depends_on:
         - db
      command: sh -c "alembic upgrade head && python main.py"

# volumes:
#    pgdata:
#   #  redis-data:
#    postgres-data:
